### PR TITLE
getPackageDbStack: Default PackageDb stack is empty

### PR DESCRIPTION
**Pull request by ttuegel**
Without a sandbox, return an empty PackageDb stack.  This does the correct thing
in most environments:
  - Under the cabal 2.0 commands, GHC gets the correct options from
    the environment file.
  - Under 'cabal exec', GHC gets the correct options from the
    GHC_ENVIRONMENT variable.
  - Under 'stack exec', GHC gets the correct options from the
    GHC_PACKAGE_PATH variable.
  - Under Nix, GHC also gets the correct options from the
    GHC_PACKAGE_PATH variable.

### CODE REVIEW

**Comment by rikvdkleij** [comment]
@ttuegel I have tried your change to get hhp working on a Cabal project that's build with `new-build` but without succes. See also #7 . It  looks like the `.ghc.environment.x86_64-darwin-8.4.4` file is not read.

**Comment by ttuegel** [comment]
@rikvdkleij I am testing by launching HHP inside `cabal v2-exec`; does that help?

**Comment by rikvdkleij** [comment]
@ttuegel Yes, that helps. Thanks! 

But it would be nicer if the `.ghc.environment.x86_64-darwin-8.4.4`  would be used 😄 

Btw, this error is displayed as first 
```
Dummy:0:0:Error:Loaded package environment from /Users/rik/haskell/quicksort/dist-newstyle/tmp/environment.-5663/.ghc.environment.x86_64-darwin-8.4.4
```

**Comment by ttuegel** [comment]
> But it would be nicer if the `.ghc.environment.x86_64-darwin-8.4.4` would be used

Yes, and I will certainly investigate why it is not!

**Comment by ttuegel** [comment]
One problem with this pull request is that `ghc-pkg` does not respect `GHC_ENVIRONMENT`, although `ghci` does; this breaks `Hhp.GhcPkg.ghcPkgListEx`.

**Pull request closed without merging**
